version: '3'
services:

  bc_registries:
    image: permitify
    environment:
      PYTHON_ENV: development
      # DATABASE_URL: 'postgres://postgres:@postgres:5432/postgres'
      THE_ORG_BOOK_BASE_URL: ${THE_ORG_BOOK_BASE_URL}
      DISCONNECTED: '${DISCONNECTED-false}'
      TEMPLATE_NAME: bc_registries
      APPLICATION_IP: 0.0.0.0
      APPLICATION_PORT: 8080
    # links:
    #   - postgres
    volumes:
      # - ../src:/app
      # - ../site_templates:/app/site_templates
      - bc_registries_wallet:/app/.indy_client/wallet
    ports:
      - 5000:8080

  worksafe_bc:
    image: permitify
    environment:
      PYTHON_ENV: development
      # DATABASE_URL: 'postgres://postgres:@postgres:5432/postgres'
      THE_ORG_BOOK_BASE_URL: ${THE_ORG_BOOK_BASE_URL}
      DISCONNECTED: '${DISCONNECTED-false}'
      TEMPLATE_NAME: worksafe_bc
      APPLICATION_IP: 0.0.0.0
      APPLICATION_PORT: 8080
    # links:
    #   - postgres
    volumes:
      # - ./src:/app
      # - ./site_templates:/app/site_templates
      - worksafe_bc_wallet:/app/.indy_client/wallet
    ports:
      - 5001:8080

  ministry_of_finance:
    image: permitify
    environment:
      PYTHON_ENV: development
      # DATABASE_URL: 'postgres://postgres:@postgres:5432/postgres'
      THE_ORG_BOOK_BASE_URL: ${THE_ORG_BOOK_BASE_URL}
      DISCONNECTED: '${DISCONNECTED-false}'
      TEMPLATE_NAME: ministry_of_finance
      APPLICATION_IP: 0.0.0.0
      APPLICATION_PORT: 8080
    # links:
    #   - postgres
    volumes:
      # - ./src:/app
      # - ./site_templates:/app/site_templates
      - ministry_of_finance_wallet:/app/.indy_client/wallet
    ports:
      - 5002:8080

  fraser_valley_health_authority:
    image: permitify
    environment:
      PYTHON_ENV: development
      # DATABASE_URL: 'postgres://postgres:@postgres:5432/postgres'
      THE_ORG_BOOK_BASE_URL: ${THE_ORG_BOOK_BASE_URL}
      DISCONNECTED: '${DISCONNECTED-false}'
      TEMPLATE_NAME: fraser_valley_health_authority
      APPLICATION_IP: 0.0.0.0
      APPLICATION_PORT: 8080
    # links:
    #   - postgres
    volumes:
      # - ../src:/app
      # - ../site_templates:/app/site_templates
      - fraser_valley_health_authority_wallet:/app/.indy_client/wallet
    ports:
      - 5003:8080

  city_of_surrey:
    image: permitify
    environment:
      PYTHON_ENV: development
      # DATABASE_URL: 'postgres://postgres:@postgres:5432/postgres'
      THE_ORG_BOOK_BASE_URL: ${THE_ORG_BOOK_BASE_URL}
      DISCONNECTED: '${DISCONNECTED-false}'
      TEMPLATE_NAME: city_of_surrey
      APPLICATION_IP: 0.0.0.0
      APPLICATION_PORT: 8080
    # links:
    #   - postgres
    volumes:
      # - ../src:/app
      # - ../site_templates:/app/site_templates
      - city_of_surrey_wallet:/app/.indy_client/wallet
    ports:
      - 5004:8080

  liquor_control_and_licensing_branch:
    image: permitify
    environment:
      PYTHON_ENV: development
      # DATABASE_URL: 'postgres://postgres:@postgres:5432/postgres'
      THE_ORG_BOOK_BASE_URL: ${THE_ORG_BOOK_BASE_URL}
      DISCONNECTED: '${DISCONNECTED-false}'
      TEMPLATE_NAME: liquor_control_and_licensing_branch
      APPLICATION_IP: 0.0.0.0
      APPLICATION_PORT: 8070
    # links:
    #   - postgres
    volumes:
      # - ../src:/app
      # - ../site_templates:/app/site_templates
      - liquor_control_and_licensing_branch_wallet:/app/.indy_client/wallet
    ports:
      - 5005:8070

  # postgres:
  #   image: postgres
  #   ports:
  #     - '5432:5432'

volumes:
  worksafe_bc_wallet:
  bc_registries_wallet:
  ministry_of_finance_wallet:
  fraser_valley_health_authority_wallet:
  city_of_surrey_wallet:
  liquor_control_and_licensing_branch_wallet:
